## Maldición de dimensionalidad y polynomial features

Daniel Conrado Monroy Madrid - 16012674

In [2]:
import numpy as np

In [2]:
from sklearn.preprocessing import PolynomialFeatures

In [9]:
import pandas as pd

## 1 variable 

In [3]:
x1 = np.random.rand(5,1)
x1

array([[0.42276015],
       [0.70187944],
       [0.64348306],
       [0.2692361 ],
       [0.51479029]])

In [13]:
poly1 = PolynomialFeatures(3)
pd.DataFrame(poly1.fit_transform(x1))

0         1         2         3
0  1.0  0.422760  0.178726  0.075558
1  1.0  0.701879  0.492635  0.345770
2  1.0  0.643483  0.414070  0.266447
3  1.0  0.269236  0.072488  0.019516
4  1.0  0.514790  0.265009  0.136424

## 2 variables

In [7]:
x2 = np.random.rand(5,2)
x2

array([[0.14958004, 0.04066589],
       [0.90255265, 0.54705627],
       [0.80468902, 0.86393601],
       [0.17605617, 0.66835398],
       [0.65669448, 0.85120369]])

In [14]:
poly2 = PolynomialFeatures(3)
pd.DataFrame(poly2.fit_transform(x2))

0         1         2         3         4         5         6         7  \
0  1.0  0.149580  0.040666  0.022374  0.006083  0.001654  0.003347  0.000910   
1  1.0  0.902553  0.547056  0.814601  0.493747  0.299271  0.735221  0.445633   
2  1.0  0.804689  0.863936  0.647524  0.695200  0.746385  0.521056  0.559420   
3  1.0  0.176056  0.668354  0.030996  0.117668  0.446697  0.005457  0.020716   
4  1.0  0.656694  0.851204  0.431248  0.558981  0.724548  0.283198  0.367080   

          8         9  
0  0.000247  0.000067  
1  0.270107  0.163718  
2  0.600608  0.644829  
3  0.078644  0.298552  
4  0.475806  0.616738

## 3 variables

In [15]:
x3 = np.random.rand(5,3)
x3

array([[0.50191855, 0.40023041, 0.27562085],
       [0.88985429, 0.28877472, 0.07215165],
       [0.5687203 , 0.84231695, 0.42931525],
       [0.53589686, 0.34644651, 0.13311114],
       [0.21613572, 0.09920779, 0.55527131]])

In [16]:
poly3 = PolynomialFeatures(3)
pd.DataFrame(poly3.fit_transform(x3))

0         1         2         3         4         5         6         7   \
0  1.0  0.501919  0.400230  0.275621  0.251922  0.200883  0.138339  0.160184   
1  1.0  0.889854  0.288775  0.072152  0.791841  0.256967  0.064204  0.083391   
2  1.0  0.568720  0.842317  0.429315  0.323443  0.479043  0.244160  0.709498   
3  1.0  0.535897  0.346447  0.133111  0.287185  0.185660  0.071334  0.120025   
4  1.0  0.216136  0.099208  0.555271  0.046715  0.021442  0.120014  0.009842   

         8         9         10        11        12        13        14  \
0  0.110312  0.075967  0.126444  0.100827  0.069435  0.080400  0.055368   
1  0.020836  0.005206  0.704623  0.228664  0.057133  0.074206  0.018541   
2  0.361620  0.184312  0.183948  0.272441  0.138859  0.403506  0.205660   
3  0.046116  0.017719  0.153902  0.099494  0.038228  0.064321  0.024713   
4  0.055087  0.308326  0.010097  0.004634  0.025939  0.002127  0.011906   

         15        16        17        18        19  
0  0.038129  0.064111  0.044150  0.030404  0.020938  
1  0.004632  0.024081  0.006017  0.001503  0.000376  
2  0.104822  0.597622  0.304598  0.155249  0.079128  
3  0.009495  0.041582  0.015977  0.006139  0.002359  
4  0.066640  0.000976  0.005465  0.030588  0.171205

## Conclusiones

A medida que aumenta la cantidad de features, la cantidad de combinaciones también lo hace. Esto se puede confirmar observando la cantidad de columnas que adquiere el dataframe:

In [21]:
print('Combinaciones 1 variable:',np.shape(pd.DataFrame(poly1.fit_transform(x1)))[1])
print('Combinaciones 2 variables:',np.shape(pd.DataFrame(poly2.fit_transform(x2)))[1])
print('Combinaciones 3 variables:',np.shape(pd.DataFrame(poly3.fit_transform(x3)))[1])

Combinaciones 1 variable: 4
Combinaciones 2 variables: 10
Combinaciones 3 variables: 20
